---
title: "🧪throw後のコード"
---

|||
|:--|:--|
|🔖|[`中断を利用するパターン`](./p_after)|
|👼|[`中断コード削除`](./a_after_stop_delete) [`ネスト修正による中断コードの移動`](./a_after_stop_move)|
|🧟|[`goto文のラベルによるジャンプ`](./z_goto) [`ホイスティング`](./z_hoisting)|

`throw` は、多くのプログラミング言語で `例外処理のために大域脱出を行う機能` として用意されている。
PythonやRubyではraise、Goではpanicという予約後を用いる。

なお、Rubyにおいては、、
ただし、大域脱出と、エラー処理を分離しているものも存在する。

近年はエラー処理以外での大域脱出はあまり、使われなくなっているため、
